# Generated by Django 4.2.30 on 2026-08-17 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_certificate_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organizer', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('result', models.CharField(blank=True, help_text='e.g. 1st Place, Finalist, Top 10, Participant', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('tech_used', models.JSONField(blank=True, default=list)),
                ('project_url', models.URLField(blank=True, help_text='Link to the project, repo, or Devpost page')),
                ('icon', models.CharField(default='bi-trophy-fill', help_text='Bootstrap icon class used when no photos are uploaded', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-date'],
            },
        ),
        migrations.CreateModel(
            name='HackathonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hackathons/')),
                ('order', models.IntegerField(default=0)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.hackathon')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
