# Generated by Django 4.2.30 on 2026-08-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_hackathon_hackathonimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='tech_used',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='highlight',
            field=models.CharField(blank=True, help_text="A distinctive, unusual detail about the experience — not a tech list. e.g. 'Pulled an all-nighter and shipped the MVP by sunrise'", max_length=150),
        ),
    ]
