# Generated by Django 4.2.30 on 2026-09-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_hackathon_tech_used_hackathon_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='description_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='description_ru',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='description_uz',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='location_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='location_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='location_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='highlight_en',
            field=models.CharField(blank=True, help_text="A distinctive, unusual detail about the experience — not a tech list. e.g. 'Pulled an all-nighter and shipped the MVP by sunrise'", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='highlight_ru',
            field=models.CharField(blank=True, help_text="A distinctive, unusual detail about the experience — not a tech list. e.g. 'Pulled an all-nighter and shipped the MVP by sunrise'", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='highlight_uz',
            field=models.CharField(blank=True, help_text="A distinctive, unusual detail about the experience — not a tech list. e.g. 'Pulled an all-nighter and shipped the MVP by sunrise'", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='location_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='location_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='location_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='result_en',
            field=models.CharField(blank=True, help_text='e.g. 1st Place, Finalist, Top 10, Participant', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='result_ru',
            field=models.CharField(blank=True, help_text='e.g. 1st Place, Finalist, Top 10, Participant', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='result_uz',
            field=models.CharField(blank=True, help_text='e.g. 1st Place, Finalist, Top 10, Participant', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
